spring.ai.google.genai.api-key= ${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

logging.level.org.springframework.ai.chat.client.advisor= debug

#postgres setup
spring.datasource.url=jdbc:postgresql://localhost:5432/springai
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring ai jdbc properties
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-postgres.sql
